version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: analyze-css
    versions:
    - 0.12.12
    - 0.12.13
  - dependency-name: commitizen
    versions:
    - 4.2.2
  - dependency-name: lodash
    versions:
    - 4.17.20
